version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
  environment:
    VITE_API_URL: http://localhost:5002
    ports:
      - "3000:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
