services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5002:5001"
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - /app/node_modules
    command: npm run dev
    restart: always
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: mauriciotacsan
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: priceClub
    ports:
      - "5432:5432"